version: "3.8"

services:
  express-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app-server
      - /app-server/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev 
